name: Print Secret

on:
  push:
    branches:
      - main

jobs:
  use-secret:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use secret safely
        run: |
          if [ -z "${{ secrets.FAKE_API_KEY }}" ]; then
            echo "❌ Secret is not set"
            exit 1
          fi
          echo "Secret is used ✅"
